# SPDX-License-Identifier: MPL-2.0

max_width = 100
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Max"

# Unstable Only:
comment_width = 100
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
wrap_comments = true
